# SPDX-License-Identifier: MIT-0
---
# tasks file for hedgedoc
- name: Set project base name
  ansible.builtin.set_fact:
    project_base_name: hedgedoc

- name: Set Project variables
  ansible.builtin.set_fact:
    project_name: "{{ project_base_name }}{{ project_suffix | default('') }}"

- name: Set Project variables
  ansible.builtin.set_fact:
    project_dir: "{{ ansible_user_dir }}/podman/{{ project_name }}"

- name: Set database service name
  ansible.builtin.set_fact:
    db_name: "{{ project_name }}_db"

- name: Set database hostname
  ansible.builtin.set_fact:
    db_hostname: "{{ db_name }}-pod"

- name: Set domain
  ansible.builtin.set_fact:
    domain: "{{ hedgedoc_domain }}"

- name: Workaround for lazy evaluation
  ansible.builtin.set_fact:
    podman_service_deploy_config:
      networks:
        - name: "{{ project_name }}_default"
          internal: false
        - name: "{{ project_name }}_db"
          internal: true
        - name: "{{ backend_network }}"
          internal: true
      volumes:
        - "{{ project_name }}-config"
        - "{{ project_name }}-uploads"
      secrets_dict: "{{ hedgedoc_config.secrets }}"
      kube_files:
        - "{{ lookup('ansible.builtin.template', 'hedgedoc.kube.j2') }}"
        - "{{ lookup('ansible.builtin.template', 'hedgedoc-env.configmap.j2') }}"
      mariadb:
        networks:
          - name: "{{ project_name }}_db"
            internal: true
        name: "{{ db_name }}"
        dbname: "{{ project_name }}"
        user: "{{ hedgedoc_config.db_user | mandatory }}"
        password: "{{ hedgedoc_config.secrets.DB_PASS | mandatory }}"
        root_password: "{{ hedgedoc_config.secrets.db_root_password | mandatory }}"
        image_tag: "{{ hedgedoc_config.mariadb_image_tag | mandatory }}"

- name: Podman service deployment
  ansible.builtin.include_role:
    name: podman_service_deploy
